parsers:
  # CXXParser should always put first
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.1.7/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.1.7/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.1.7/include/IAgoraService.h'

  - name: AddNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      customHeaderFileNamePrefix: 'Custom'
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.1.7/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.1.7/include/*.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.1.7/custom_headers/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.1.7/include/IAgoraService.h'

  - name: PointerToArrayParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      configJsonFilePath: ./pointer_to_array.json
  - name: OrderNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: FixEnumConstantParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      configJsonFilePath: ./param_type_list.json
  - name: RemoveNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      configJsonFilePath: ./remove_node_list.json

# defines_macros:
#   - __IRIS_WEB__

renderers:
  - path: ../index.ts

version: 2.1.7
