parsers:
  - name: CXXParser
    package: '@agoraio-extensions/cxx-parser'
    args:
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include/IAgoraRtmService.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include/IAgoraService.h'

  - name: AddNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      customHeaderFileNamePrefix: 'Custom'
      includeHeaderDirs:
        - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include'
      parseFiles:
        include:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include/*.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/custom_headers/*.h'
        exclude:
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include/IAgoraRtmService.h'
          - '@agoraio-extensions/terra_shared_configs:headers/rtm_2.2.3/include/IAgoraService.h'

  - name: RemoveNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      ignoreDefaultConfig: true
      configFilePath: ./remove_node_list.ts
  - name: PointerToArrayParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      ignoreDefaultConfig: true
      configFilePath: ./pointer_to_array.ts
  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      ignoreDefaultConfig: true
      configFilePath: ./rename_member_function_param_type_list.ts
  - name: ReturnTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      convertReturnToVoid: false
      ignoreDefaultConfig: true
      configFilePath: ./fixed_return_type_list.ts
  - name: FixEnumConstantParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: OrderNodeParser
    package: '@agoraio-extensions/terra_shared_configs'
  - name: UpdateSimpleTypeParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      parserDefaultValue: true
      ignoreDefaultConfig: true
      configFilePath: ./c_to_ts_config.ts
  - name: TsCommentParser
    package: '@agoraio-extensions/terra_shared_configs'
    args:
      language: 'ts'

renderers:
  - path: ../index.ts

version: 2.2.3
