import { GetHistoryMessagesOptions, RtmChannelType } from './AgoraRtmBase';

/// Generated by terra, DO NOT MODIFY BY HAND.

/**
 * The IRtmHistory class.
 *
 * This class provides the rtm history methods that can be invoked by your app.
 */
export abstract class IRtmHistory {
  /**
   * gets history messages in the channel.
   *
   * @param [in] channelName The name of the channel.
   * @param [in] channelType The type of the channel.
   * @param [in] options The query options.
   * @param [out] requestId The related request id of this operation.
   * @return
   * - 0: Success.
   * - < 0: Failure.
   */
  abstract getMessages(
    channelName: string,
    channelType: RtmChannelType,
    options: GetHistoryMessagesOptions
  ): number;
}
