# Simple workflow for deploying static content to GitHub Pages
name: TypeDoc

on:
  # Runs on new releases
  release:
    types: [published]
  push:
    branches: [main]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build TypeDoc
        run: yarn doc
      - name: Zip It Up 🤐
        run: |
          zip -r agora-react-native-rtm-docs.zip docs
      - name: Upload Artifact ⬆️
        uses: actions/upload-artifact@v3
        with:
          name: agora-react-native-rtm-docs.zip
          path: agora-react-native-rtm-docs.zip
      - name: Upload Doc Archive to GitHub release ⬆️
        if: github.event.release
        uses: svenstaro/upload-release-action@2.6.0
        with:
          file: agora-react-native-rtm-docs.zip
          asset_name: agora-react-native-rtm-docs.zip
          tag: ${{ github.ref_name }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload docs directory
          path: 'docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
